# Discretization relative step
delta: 0.08

# Number of intervals in the (\pi, \theta) mesh
imax: 100

# Horizontal coordinate of right border, in km
x_right: 370 

# Define surface age
age_surf: -50

fig_age_max: 1000 #max age (kyr) for the age contour plots
fig_age_spacing: 10 #spacing for the age (kyr) contour plots
fig_age_spacing_labels: 100 #spacing for the labels (kyr) of the age color bars

traj_step: 1 #Plot only one srreamline every traj_step

max_depth: 3310. #Max depth in the drilling
step_depth: 1.  #Depth step in the drilling

create_figs: True  #If we create figures or not.