# Discretization relative step
delta: 0.08

# Number of intervals in the (\pi, \theta) mesh
imax: 100

#Parameter for glacial/interglacial accumulation change
beta: 0.015 

#Total ice thickness at drilling location
thickness: 3767 

x_right: 370 #Horizontal coordinate of right border, in km

fig_age_max: 1000 #max age (kyr) for the age contour plots
fig_age_spacing: 10 #spacing for the age (kyr) contour plots
fig_age_spacing_labels: 100 #spacing for the labels (kyr) of the age color bars

traj_step: 10 #Plot only one srreamline every traj_step

max_depth: 3310. #Max depth in the drilling

create_figs: True  #If we create figures or not.