# Discretization relative step
delta: 0.01

# Number of intervals in the (\pi, \theta) mesh
imax: 1000

# Horizontal coordinate of right border, in km
x_right: 370 
# Horizontal step for the computation of the total flux Q, in km
x_step: 1.

# Define surface age
age_surf: 0

fig_age_max: 1000 #max age (kyr) for the age contour plots
fig_age_spacing: 10 #spacing for the age (kyr) contour plots
fig_age_spacing_labels: 100 #spacing for the labels (kyr) of the age color bars

traj_step: 10 #Plot only one srreamline every traj_step

ic_name: 'Vostok'
ic_x: 370.  # X coordinate of the drilling, in km
ic_max_depth: 3349. #Max depth in the drilling
ic_step_depth: 1.  #Depth step in the drilling

create_figs: True  #If we create figures or not.
fig_format: 'pdf'
output_ic: True