# Discretization relative step
delta: 0.08

# Number of nodes following \pi and \theta
imax: 100

#Parameter for glacial/interglacial accumulation change
beta: 0.015 

#Total ice thickness at drilling location
thickness: 3767 

x_right: 370 #Horizontal coordinate of right border, in km

iso_spacing: 100000 #isochrone spacing in graphs
iso_max: 600000  #max age of isochrones

max_depth: 3310. #Max depth in the drilling

create_figs: True  #If we create figures or not.